#!/usr/bin/env python3
"""
Sync briefs from briefs/ to src/data/ and generate the index.
Run this after generating a new brief with /workflow.
"""

import json
import shutil
from pathlib import Path

BRIEFS_DIR = Path(__file__).parent.parent / "briefs"
DATA_DIR = Path(__file__).parent.parent / "src" / "data"

def sync_briefs():
    """Copy JSON briefs to src/data and generate index."""

    # Ensure data dir exists
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    # Clean old files in data dir (except index.ts)
    for old_file in DATA_DIR.glob("*.json"):
        old_file.unlink()
        print(f"Removed: {old_file.name}")

    # Remove symlinks as well
    latest_link = DATA_DIR / "latest.json"
    if latest_link.is_symlink():
        latest_link.unlink()
        print("Removed: latest.json symlink")

    # Find all JSON briefs
    briefs = sorted(BRIEFS_DIR.glob("CSE_Intel_Brief_*.json"), reverse=True)

    if not briefs:
        print("No briefs found in briefs/ directory")
        return

    # Copy each brief to src/data
    brief_entries = []
    for brief_path in briefs:
        # Copy to data dir
        dest = DATA_DIR / brief_path.name
        shutil.copy2(brief_path, dest)

        # Read meta for index
        with open(brief_path) as f:
            data = json.load(f)

        brief_id = brief_path.stem  # CSE_Intel_Brief_20260307
        brief_entries.append({
            "id": brief_id,
            "filename": brief_path.name,
            "timestamp": data.get("meta", {}).get("timestamp", ""),
            "threatLevel": data.get("meta", {}).get("threatLevel", ""),
        })
        print(f"Synced: {brief_path.name}")

    # Generate TypeScript index
    index_content = '''// Auto-generated by scripts/sync_briefs.py
// Do not edit manually - run: python scripts/sync_briefs.py

import type { BriefCycle } from '../types/brief'

'''

    # Add imports
    for entry in brief_entries:
        var_name = entry["id"].replace("-", "_")
        index_content += f'import {var_name} from "./{entry["filename"]}"\n'

    index_content += '''
export const allBriefs = [
'''

    for entry in brief_entries:
        var_name = entry["id"].replace("-", "_")
        index_content += f'  {{ id: "{entry["id"]}", data: {var_name} as unknown as BriefCycle }},\n'

    index_content += '''].sort((a, b) =>
  new Date(b.data.meta.timestamp).getTime() - new Date(a.data.meta.timestamp).getTime()
)

export const briefsById = Object.fromEntries(
  allBriefs.map(b => [b.id, b.data])
)
'''

    # Write index
    index_path = DATA_DIR / "index.ts"
    with open(index_path, "w") as f:
        f.write(index_content)

    print(f"\nGenerated: src/data/index.ts with {len(brief_entries)} brief(s)")
    print("Run 'npm run dev' to view")

if __name__ == "__main__":
    sync_briefs()
