// Auto-generated by scripts/sync_briefs.py
// Do not edit manually - run: python scripts/sync_briefs.py

import type { BriefCycle } from '../types/brief'

import CSE_Intel_Brief_20260307_024919 from "./CSE_Intel_Brief_20260307_024919.json"
import CSE_Intel_Brief_20260307 from "./CSE_Intel_Brief_20260307.json"
import CSE_Intel_Brief_20260306 from "./CSE_Intel_Brief_20260306.json"

export const allBriefs = [
  { id: "CSE_Intel_Brief_20260307_024919", data: CSE_Intel_Brief_20260307_024919 as unknown as BriefCycle },
  { id: "CSE_Intel_Brief_20260307", data: CSE_Intel_Brief_20260307 as unknown as BriefCycle },
  { id: "CSE_Intel_Brief_20260306", data: CSE_Intel_Brief_20260306 as unknown as BriefCycle },
].sort((a, b) =>
  new Date(b.data.meta.timestamp).getTime() - new Date(a.data.meta.timestamp).getTime()
)

export const briefsById = Object.fromEntries(
  allBriefs.map(b => [b.id, b.data])
)
